# Generated by Django 6.0.1 on 2026-07-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_tripstatushistory_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='estimated_duration',
            field=models.PositiveIntegerField(help_text='Estimated Duration (in minutes)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
