# Generated by Django 6.0.7 on 2026-07-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('emergency_contact', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
